/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dftc_libonvifvideo_OnvifVideoUtil */

#ifndef _Included_com_dftc_libonvifvideo_OnvifVideoUtil
#define _Included_com_dftc_libonvifvideo_OnvifVideoUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dftc_libonvifvideo_OnvifVideoUtil
 * Method:    initVideo
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dftc_libonvifvideo_OnvifVideoUtil_initVideo
  (JNIEnv *, jobject,jstring);

/*
 * Class:     com_dftc_libonvifvideo_OnvifVideoUtil
 * Method:    releaseVideo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_dftc_libonvifvideo_OnvifVideoUtil_releaseVideo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dftc_libonvifvideo_OnvifVideoUtil
 * Method:    addIPC
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dftc_libonvifvideo_OnvifVideoUtil_addIPC
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_dftc_libonvifvideo_OnvifVideoUtil
 * Method:    deleteIPC
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dftc_libonvifvideo_OnvifVideoUtil_deleteIPC
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dftc_libonvifvideo_OnvifVideoUtil
 * Method:    sendIPCData
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_dftc_libonvifvideo_OnvifVideoUtil_sendIPCData
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_dftc_libonvifvideo_OnvifVideoUtil
 * Method:    stopIPCData
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dftc_libonvifvideo_OnvifVideoUtil_stopIPCData
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dftc_libonvifvideo_OnvifVideoUtil
 * Method:    setVideoInfo
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_dftc_libonvifvideo_OnvifVideoUtil_setVideoInfo
  (JNIEnv *, jobject,jlong, jint, jint, jint);

JNIEXPORT jlong JNICALL Java_com_dftc_libonvifvideo_OnvifVideoUtil_crc32
(JNIEnv *, jobject,jstring);

#ifdef __cplusplus
}
#endif
#endif
